/*
Họ và tên: Phạm Minh Hiếu
MSSV: 2011063873
Lớp: 20DTHB4
*/

-- Tạo database 
CREATE DATABASE QLCB
ON
	(NAME='QLCB_DATA',
	FILENAME='H:\BAITAP\QLCB.MDF')
LOG ON
	(NAME='QLCB_LOG',
	FILENAME='H:\BAITAP\QLCB.LDF')
GO

USE QLCB
GO

--Tạo bảng máy bay
CREATE TABLE MAYBAY
(
	MAMB INT,
	LOAI VARCHAR(50),
	TAMBAY INT,

	CONSTRAINT PK_MAYBAY_MAMB PRIMARY KEY (MAMB)
)
GO

--Tạo bảng chuyến bay
CREATE TABLE CHUYENBAY
(
	MACB CHAR(5),
	GADI VARCHAR(50),
	GADEN VARCHAR(50),
	DODAI INT,
	GIODI TIME,
	GIODEN TIME,
	CHIPHI INT,
	MAMB INT,

	CONSTRAINT PK_CHUYENBAY_MACB PRIMARY KEY (MACB),

	CONSTRAINT FK_CHUYENBAY_MAMB FOREIGN KEY (MAMB) REFERENCES MAYBAY(MAMB)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)
GO

--Tạo bảng nhân viên
CREATE TABLE NHANVIEN
(
	MANV CHAR(9),
	TEN NVARCHAR(50),
	LUONG INT

	CONSTRAINT PK_NHANVIEN_MANV PRIMARY KEY (MANV)
)
GO

--Tạo bảng chứng nhận
CREATE TABLE CHUNGNHAN
(
	MANV CHAR(9),
	MAMB INT,

	CONSTRAINT PK_CHUNGNHAN_MANV_MAMB PRIMARY KEY (MANV, MAMB),

	CONSTRAINT FK_CHUNGNHAN_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	CONSTRAINT FK_CHUNGNHAN_MAMB FOREIGN KEY (MAMB) REFERENCES MAYBAY(MAMB)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)
GO

--Câu 1
SELECT MACB [Mã chuyến bay], GADI [Ga đi],GADEN [Ga đến]
FROM CHUYENBAY
WHERE GADEN LIKE 'DAD'
GO

--Câu 2
SELECT MAMB [Mã máy bay], LOAI [Loại], TAMBAY [Tầm bay]
FROM MAYBAY
WHERE TAMBAY > 10000
GO

--Câu 3
SELECT MANV [Mã nhân viên], TEN [Tên], LUONG [Lương]
FROM NHANVIEN
WHERE LUONG < 10000
GO

--Câu 4
SELECT MACB [Mã chuyến bay], GADI [Ga đi], GADEN [Ga đến], DODAI [Độ dài]
FROM CHUYENBAY
WHERE DODAI BETWEEN 8000 AND 10000
GO

--Câu 5
SELECT MACB [Mã chuyến bay], GADI [Ga đi], GADEN [Ga đến]
FROM CHUYENBAY
WHERE GADI LIKE 'SGN' AND GADEN LIKE 'BMV'
GO

--Câu 6
SELECT COUNT(GADI) [Số lượng chuyến bay xuất phát từ Hồ Chí Minh]
FROM CHUYENBAY
WHERE GADI LIKE 'SGN'
GO

--Câu 7
SELECT COUNT(LOAI) [Số lượng máy bay boeing]
FROM MAYBAY
WHERE LOAI LIKE 'Boeing%'
GO

--Câu 8
SELECT SUM(LUONG) [Tổng lương phải trả]
FROM NHANVIEN
GO

--Câu 9
SELECT CN.MANV [Mã nhân viên], NV.TEN [Họ và tên], LOAI
FROM CHUNGNHAN CN, NHANVIEN NV, MAYBAY MB
WHERE CN.MANV = NV.MANV AND MB.MAMB = CN.MAMB AND MB.LOAI LIKE 'Boeing%'
GROUP BY CN.MANV, TEN, LOAI
GO

--Câu 10
SELECT CN.MANV [Mã nhân viên], NV.TEN [Họ và tên], mb.MAMB [Mã máy bay],LOAI [Loại máy bay]
FROM CHUNGNHAN CN, NHANVIEN NV, MAYBAY MB
WHERE CN.MANV = NV.MANV AND MB.MAMB = CN.MAMB AND MB.MAMB LIKE '747'
GROUP BY CN.MANV, TEN, MB.MAMB, LOAI
GO

--Câu 11
SELECT MB.MAMB [Mã máy bay], NV.TEN [Họ và tên] 
FROM MAYBAY MB, CHUNGNHAN CN, NHANVIEN NV
WHERE MB.MAMB = CN.MAMB AND CN.MANV = NV.MANV AND NV.TEN LIKE N'Nguyễn%'
GO

--Câu 12
SELECT NV.MANV [Mã nhân viên], NV.TEN 
FROM MAYBAY MB
INNER JOIN  CHUNGNHAN CN ON MB.MAMB = CN.MAMB AND 
						

