CREATE DATABASE TACGIA
ON
	(NAME='TACGIA_DATA',
	FILENAME='H:\BAITAP\TACGIA.MDF')
LOG ON
	(NAME='TACGIA_LOG',
	FILENAME='H:\BAITAP\TACGIA.LDF')
GO

USE TACGIA
GO

--Tạo bảng tác giả
CREATE TABLE TACGIA
(
	MATG CHAR(5),
	HOTEN VARCHAR(20) NOT NULL,
	DIACHI VARCHAR(50) NOT NULL,
	NGSINH SMALLDATETIME NOT NULL,
	SODT VARCHAR(15) UNIQUE NOT NULL,

	CONSTRAINT PK_TACGIA_MATG PRIMARY KEY (MATG)
)GO

--Tạo bảng sách
CREATE TABLE SACH
(
	MASACH CHAR(5),
	TENSACH VARCHAR(25) NOT NULL,
	THELOAI VARCHAR(25) NOT NULL,

	CONSTRAINT PK_SACH_MASACH PRIMARY KEY (MASACH)
)
GO

--Tạo bảng tác giả sách
CREATE TABLE TACGIA_SACH
(
	MATG CHAR(5),
	MASACH CHAR(5) NOT NULL,

	CONSTRAINT PK_TGSACH_MATG PRIMARY KEY (MATG),

	CONSTRAINT FK_TGSACH_MATG FOREIGN KEY (MATG) REFERENCES TACGIA(MATG)
	ON UPDATE CASCADE
	ON DELETE CASCADE,

	CONSTRAINT FK_TGSACH_MASACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
)

--Tạo bảng phát hành
CREATE TABLE PHATHANH
(
	MAPH CHAR(5),
	MASACH CHAR(5) NOT NULL,
	NGAYPH SMALLDATETIME NOT NULL,
	SOLUONG INT NOT NULL,
	NHAXUATBAN VARCHAR(20) NOT NULL,

	CONSTRAINT PK_PHATHANH_MAPH PRIMARY KEY (MAPH),

	CONSTRAINT FK_PHATHANH_MASACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)
GO

--Câu 2a
SELECT TG.MATG, TG.HOTEN, TG.SODT
FROM TACGIA TG, SACH S, TACGIA_SACH TGS, PHATHANH PH
WHERE TG.MATG = TGS.MATG AND S.MASACH = TGS.MASACH AND PH.MASACH = S.MASACH AND THELOAI LIKE 'Van hoc%' AND PH.NHAXUATBAN LIKE 'Tre%'
GO

--Câu 2b
SELECT PH.NHAXUATBAN, COUNT(S.THELOAI)
FROM PHATHANH PH, SACH S
WHERE PH.MASACH = S.MASACH
GROUP BY PH.NHAXUATBAN
GO

--Câu 2c
SELECT TG.MATG, TG.HOTEN
FROM TACGIA TG, SACH S, TACGIA_SACH TGS , PHATHANH PH
WHERE TG.MATG = TGS.MATG AND PH.MASACH = TGS.MASACH AND S.MASACH = PH.MASACH
GO

--Câu 3
CREATE TRIGGER KTRA
ON PHATHANH
FOR INSERT, UPDATE
AS
	SELECT PH.NGAYPH, TG.NGSINH FROM PHATHANH PH, TACGIA TG
	WHERE PH.NGAYPH > TG.NGSINH
BEGIN
	RAISERROR(N'=====ACCESS DENIED=====',16,1)
    ROLLBACK TRAN
END