/*
Họ và tên: Phạm Minh Hiếu
MSSV: 2011063873
Lớp: 20DTHB4
*/

-- Tạo database 
CREATE DATABASE QLDA
ON
	(NAME='QLDA_DATA',
	FILENAME='H:\BAITAP\QLDA.MDF')
LOG ON
	(NAME='QLDA_LOG',
	FILENAME='H:\BAITAP\QLDA.LDF')
GO

USE QLDA
GO

--Tạo bảng nhà cung cấp
CREATE TABLE NCC
(
	MANCC CHAR(5),
	TEN VARCHAR(40),
	HESO INT,
	THPHO VARCHAR(20),

	CONSTRAINT PK_NCC_MANCC PRIMARY KEY (MANCC)
)
GO

--Tạo bảng vật tư
CREATE TABLE VATTU
(
	MAVT CHAR(5),
	TEN VARCHAR(40),
	MAU VARCHAR(15),
	TRLUONG FLOAT,
	THPHO VARCHAR(20),

	CONSTRAINT PK_VATTU_MAVT PRIMARY KEY (MAVT),
)
GO

--Tạo bảng dự án
CREATE TABLE DUAN
(
	MADA CHAR(5),
	TEN VARCHAR(40),
	THPHO VARCHAR(20),

	CONSTRAINT PK_DUAN_MADA PRIMARY KEY (MADA)
)
GO

--Tạo bảng cung cấp
CREATE TABLE CC
(
	MANCC CHAR(5),
	MAVT CHAR(5),
	MADA CHAR(5),
	SLUONG INT,

	CONSTRAINT PK_CC PRIMARY KEY (MANCC, MAVT, MADA),
	
	CONSTRAINT FK_CC_MANCC FOREIGN KEY (MANCC) REFERENCES NCC(MANCC)
	ON UPDATE CASCADE
	ON DELETE CASCADE,	

	CONSTRAINT FK_CC_MAVT FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	
	CONSTRAINT FK_CC_MADA FOREIGN KEY (MADA) REFERENCES DUAN(MADA)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)
GO

--Câu 1
SELECT MAVT, MAU, THPHO
FROM VATTU
WHERE THPHO NOT LIKE 'Ha Noi' AND TRLUONG > 10
GO

--Câu 2
SELECT *
FROM DUAN
GO

--Câu 3
SELECT *
FROM DUAN 
WHERE THPHO LIKE 'TpHCM'
GO

--Câu 4
SELECT NCC.TEN, CC.MADA
FROM CC, NCC
WHERE NCC.MANCC = CC.MANCC AND MADA LIKE 'J1'
GO

--Câu 5
SELECT NCC.TEN, VT.TEN, D.TEN, CC.SLUONG 
FROM NCC, VATTU VT, DUAN D, CC
WHERE NCC.MANCC = CC.MANCC AND VT.MAVT = CC.MAVT AND D.MADA = CC.MADA AND CC.SLUONG > 300 AND CC.SLUONG < 750
GO
